on:
  push:
    branches:
      - master
    








jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      
      - uses: actions/checkout@v3  
      - name: "login to doker hub"
        run: winpty docker login --username ${{secrets.DOCKERNAME}} --password ${{secrets.DOCKERPASSWORD}}
      - name: "building image"
        run: winpty docker build -t ${{secrets.DOCKERNAME}}/os-2_task .
      - name: "push image"
        run: winpty docker push ${{secrets.DOCKERNAME}}/os-2_task
