on:
  push:
    branches:
      - master
    








jobs:
  build:
    runs-on: ubuntu-latest
    
 


    steps:
      
      - uses: actions/checkout@v3  
      - name: "login to doker hub"
        run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}}
      - name: "building image"
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/os-2_task .
      - name: "push image"
        run: docker push ${{secrets.DOCKER_USERNAME}}/os-2_task
